import React from 'react';
import { WhatsAppIcon } from '../SocialIcons';
import {
  // Spa, Bem-estar & Cuidado
  Sparkles,
  Sparkle,
  Flower,
  Flower2,
  Leaf,
  Droplets,
  Droplet,
  Flame,
  Sun,
  Moon,
  Cloud,
  Wind,
  Waves,
  Feather,
  Heart,
  HeartHandshake,
  Smile,
  Trees,
  Palmtree,
  Bath,
  ShowerHead,
  Coffee,
  CupSoda,
  Wine,
  Utensils,
  Music,
  Headphones,
  Radio,

  // Luxo, Presentes & Celebração
  Gift,
  Crown,
  Gem,
  Award,
  Medal,
  Trophy,
  Star,
  Ribbon,
  Wand2,
  Tag,
  Bookmark,

  // Confiança, Segurança & Qualidade
  Shield,
  ShieldCheck,
  Check,
  CheckCircle,
  CheckCircle2,
  ThumbsUp,
  Zap,
  Activity,
  HeartPulse,
  Eye,
  Camera,
  Image,

  // Tempo, Localização & Navegação
  Clock,
  Clock3,
  Calendar,
  CalendarCheck,
  CalendarDays,
  MapPin,
  Navigation,
  Compass,
  LocateFixed,
  Globe,
  Home,
  Building,
  Store,

  // Contato, Comunicação & Apoio
  MessageCircle,
  MessageSquare,
  Phone,
  PhoneCall,
  Mail,
  Send,
  Share2,
  HelpCircle,
  Info,
  Bell,
  Volume2,

  // Outros / Utilidades
  Sliders,
  SlidersHorizontal,
  Search,
  Filter,
  CheckCheck,
  CircleDot,
  Key,
  Lock,
  Unlock,
  Package,
  ShoppingBag,
  Ticket,
  Plus,
  PlusCircle,
  Footprints,
  GlassWater,
  Lamp,
  Users,
  Scissors,
  SmilePlus,
  VolumeX,
  ExternalLink,
  RotateCcw,
  X,
  Menu,

  // Setas & Direções
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ArrowUpRight,
  ArrowDownRight,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';

export interface IconDefinition {
  name: string;
  label: string;
  category: 'spa' | 'luxo' | 'tempo-local' | 'contato' | 'setas' | 'geral';
  tags: string[];
  component: React.ComponentType<{ className?: string; size?: number; style?: React.CSSProperties }>;
}

export const ICON_REGISTRY: Record<string, IconDefinition> = {
  // SPA & Bem-Estar
  Sparkles: {
    name: 'Sparkles',
    label: 'Brilho Zen',
    category: 'spa',
    tags: ['brilho', 'magia', 'spa', 'ritual', 'energia', 'estrelas', 'glow'],
    component: Sparkles,
  },
  Sparkle: {
    name: 'Sparkle',
    label: 'Centelha',
    category: 'spa',
    tags: ['centelha', 'brilho', 'delicado', 'luz'],
    component: Sparkle,
  },
  Droplets: {
    name: 'Droplets',
    label: 'Gotas de Água',
    category: 'spa',
    tags: ['agua', 'gotas', 'head spa', 'arco hidrico', 'hidratacao', 'pureza'],
    component: Droplets,
  },
  Droplet: {
    name: 'Droplet',
    label: 'Gota Serena',
    category: 'spa',
    tags: ['gota', 'oleo essencial', 'aroma', 'agua'],
    component: Droplet,
  },
  Flower: {
    name: 'Flower',
    label: 'Flor de Lótus',
    category: 'spa',
    tags: ['flor', 'lotus', 'zen', 'relaxamento', 'beleza', 'botanica'],
    component: Flower,
  },
  Flower2: {
    name: 'Flower2',
    label: 'Flor Floral',
    category: 'spa',
    tags: ['flor', 'florescer', 'delicadeza', 'aroma'],
    component: Flower2,
  },
  Leaf: {
    name: 'Leaf',
    label: 'Folha Botânica',
    category: 'spa',
    tags: ['folha', 'natureza', 'organico', 'cha', 'ervas'],
    component: Leaf,
  },
  Flame: {
    name: 'Flame',
    label: 'Chama / Vela',
    category: 'spa',
    tags: ['chama', 'vela', 'calor', 'pedras quentes', 'fogo', 'aconchego'],
    component: Flame,
  },
  Feather: {
    name: 'Feather',
    label: 'Pena Suave',
    category: 'spa',
    tags: ['pena', 'leveza', 'suavidade', 'toque', 'delicado'],
    component: Feather,
  },
  Heart: {
    name: 'Heart',
    label: 'Coração & Afeto',
    category: 'spa',
    tags: ['coracao', 'amor', 'afeto', 'cuidado', 'acolhimento', 'presente'],
    component: Heart,
  },
  HeartHandshake: {
    name: 'HeartHandshake',
    label: 'Acolhimento',
    category: 'spa',
    tags: ['maos', 'acolhimento', 'confianca', 'cuidado'],
    component: HeartHandshake,
  },
  Smile: {
    name: 'Smile',
    label: 'Sorriso & Bem-Estar',
    category: 'spa',
    tags: ['sorriso', 'alegria', 'leveza', 'renovacao'],
    component: Smile,
  },
  Bath: {
    name: 'Bath',
    label: 'Banho de Imersão',
    category: 'spa',
    tags: ['banho', 'banheira', 'imersao', 'escalda-pes'],
    component: Bath,
  },
  ShowerHead: {
    name: 'ShowerHead',
    label: 'Ducha & Arco Hídrico',
    category: 'spa',
    tags: ['ducha', 'jatos', 'arco hidrico', 'head spa'],
    component: ShowerHead,
  },
  Waves: {
    name: 'Waves',
    label: 'Ondas & Fluidez',
    category: 'spa',
    tags: ['ondas', 'agua', 'fluidez', 'mar', 'rio'],
    component: Waves,
  },
  Wind: {
    name: 'Wind',
    label: 'Brisa Leve',
    category: 'spa',
    tags: ['vento', 'brisa', 'aroma', 'ar fresco'],
    component: Wind,
  },
  Sun: {
    name: 'Sun',
    label: 'Sol Radiante',
    category: 'spa',
    tags: ['sol', 'luz', 'calor', 'vitalidade', 'dia'],
    component: Sun,
  },
  Moon: {
    name: 'Moon',
    label: 'Lua Serena',
    category: 'spa',
    tags: ['lua', 'sono', 'noite', 'descanso', 'calmaria'],
    component: Moon,
  },
  Cloud: {
    name: 'Cloud',
    label: 'Nuvem Conforto',
    category: 'spa',
    tags: ['nuvem', 'maciez', 'conforto', 'toalha'],
    component: Cloud,
  },
  Coffee: {
    name: 'Coffee',
    label: 'Chá / Café Artesanal',
    category: 'spa',
    tags: ['cha', 'cafe', 'infusao', 'boas vindas', 'caneca'],
    component: Coffee,
  },
  CupSoda: {
    name: 'CupSoda',
    label: 'Welcome Drink',
    category: 'spa',
    tags: ['drink', 'taca', 'bebida', 'cristal'],
    component: CupSoda,
  },
  Wine: {
    name: 'Wine',
    label: 'Taça de Celebração',
    category: 'spa',
    tags: ['vinho', 'taca', 'brinde', 'celebracao'],
    component: Wine,
  },
  Music: {
    name: 'Music',
    label: 'Trilha Sonora Zen',
    category: 'spa',
    tags: ['musica', 'som', 'frequencia', 'harmonia'],
    component: Music,
  },
  Headphones: {
    name: 'Headphones',
    label: 'Fones Sensoriais',
    category: 'spa',
    tags: ['som', 'audicao', 'fones', 'meditacao'],
    component: Headphones,
  },

  // Luxo & Celebração
  Gift: {
    name: 'Gift',
    label: 'Gift Card / Presente',
    category: 'luxo',
    tags: ['presente', 'gift card', 'voucher', 'surpresa', 'carinho'],
    component: Gift,
  },
  Crown: {
    name: 'Crown',
    label: 'Coroa / Exclusivo',
    category: 'luxo',
    tags: ['coroa', 'nobreza', 'exclusivo', 'vip', 'premium'],
    component: Crown,
  },
  Gem: {
    name: 'Gem',
    label: 'Joia Preciosa',
    category: 'luxo',
    tags: ['joia', 'diamante', 'pedra preciosa', 'luxo', 'raridade'],
    component: Gem,
  },
  Star: {
    name: 'Star',
    label: 'Estrela / Destaque',
    category: 'luxo',
    tags: ['estrela', 'avaliacao', 'destaque', 'favorito', 'ouro'],
    component: Star,
  },
  Award: {
    name: 'Award',
    label: 'Premiação & Selo',
    category: 'luxo',
    tags: ['premio', 'selo', 'reconhecimento', 'qualidade'],
    component: Award,
  },
  Medal: {
    name: 'Medal',
    label: 'Medalha de Honra',
    category: 'luxo',
    tags: ['medalha', 'excelencia', 'conquista'],
    component: Medal,
  },
  Trophy: {
    name: 'Trophy',
    label: 'Troféu Excelência',
    category: 'luxo',
    tags: ['trofeu', 'vencedor', 'ouro', 'campeao'],
    component: Trophy,
  },
  Ribbon: {
    name: 'Ribbon',
    label: 'Laço de Fita',
    category: 'luxo',
    tags: ['laco', 'fita', 'presente', 'embrulho'],
    component: Ribbon,
  },
  Wand2: {
    name: 'Wand2',
    label: 'Varinha de Encanto',
    category: 'luxo',
    tags: ['magia', 'transformacao', 'encanto'],
    component: Wand2,
  },
  Tag: {
    name: 'Tag',
    label: 'Etiqueta Especial',
    category: 'luxo',
    tags: ['tag', 'etiqueta', 'preco', 'condicao'],
    component: Tag,
  },
  Bookmark: {
    name: 'Bookmark',
    label: 'Marcador Favorito',
    category: 'luxo',
    tags: ['marcador', 'salvar', 'favorito'],
    component: Bookmark,
  },

  // Tempo, Localização & Navegação
  Clock: {
    name: 'Clock',
    label: 'Horário / Tempo',
    category: 'tempo-local',
    tags: ['relogio', 'horario', 'tempo', 'minutos', 'duracao', 'agendamento'],
    component: Clock,
  },
  Clock3: {
    name: 'Clock3',
    label: 'Relógio Pontual',
    category: 'tempo-local',
    tags: ['relogio', 'pontualidade', 'expediente'],
    component: Clock3,
  },
  Calendar: {
    name: 'Calendar',
    label: 'Calendário / Data',
    category: 'tempo-local',
    tags: ['calendario', 'data', 'dia', 'agenda', 'reserva'],
    component: Calendar,
  },
  CalendarCheck: {
    name: 'CalendarCheck',
    label: 'Horário Confirmado',
    category: 'tempo-local',
    tags: ['calendario', 'confirmado', 'agendado', 'reserva feita'],
    component: CalendarCheck,
  },
  MapPin: {
    name: 'MapPin',
    label: 'Localização / Pin',
    category: 'tempo-local',
    tags: ['pin', 'mapa', 'localizacao', 'endereco', 'loja', 'bandeirante'],
    component: MapPin,
  },
  Navigation: {
    name: 'Navigation',
    label: 'Traçar Rota / Waze',
    category: 'tempo-local',
    tags: ['navegacao', 'rota', 'gps', 'waze', 'maps', 'caminho'],
    component: Navigation,
  },
  Compass: {
    name: 'Compass',
    label: 'Bússola Sentido',
    category: 'tempo-local',
    tags: ['bussola', 'direcao', 'guia', 'orientacao'],
    component: Compass,
  },
  Globe: {
    name: 'Globe',
    label: 'Mundo / Global',
    category: 'tempo-local',
    tags: ['mundo', 'globo', 'site', 'coreano'],
    component: Globe,
  },
  Home: {
    name: 'Home',
    label: 'Santuário / Casa',
    category: 'tempo-local',
    tags: ['casa', 'lar', 'espaco', 'acolhedor'],
    component: Home,
  },
  Store: {
    name: 'Store',
    label: 'Loja Física',
    category: 'tempo-local',
    tags: ['loja', 'fachada', 'comercio', 'terreo'],
    component: Store,
  },

  // Contato & Comunicação
  WhatsApp: {
    name: 'WhatsApp',
    label: 'WhatsApp Oficial',
    category: 'contato',
    tags: ['whatsapp', 'wpp', 'mensagem', 'contato', 'agendar', 'conversa'],
    component: WhatsAppIcon,
  },
  MessageCircle: {
    name: 'MessageCircle',
    label: 'WhatsApp Oficial',
    category: 'contato',
    tags: ['whatsapp', 'wpp', 'mensagem', 'chat', 'conversa', 'recepcao'],
    component: WhatsAppIcon,
  },
  MessageSquare: {
    name: 'MessageSquare',
    label: 'Depoimento / Balão',
    category: 'contato',
    tags: ['conversa', 'review', 'opiniao', 'depoimento'],
    component: MessageSquare,
  },
  Phone: {
    name: 'Phone',
    label: 'Telefone Ligação',
    category: 'contato',
    tags: ['telefone', 'ligar', 'chamada', 'contato direto'],
    component: Phone,
  },
  Mail: {
    name: 'Mail',
    label: 'E-mail Formal',
    category: 'contato',
    tags: ['email', 'carta', 'contato'],
    component: Mail,
  },
  Send: {
    name: 'Send',
    label: 'Enviar / Encaminhar',
    category: 'contato',
    tags: ['enviar', 'mensagem', 'solicitar'],
    component: Send,
  },
  HelpCircle: {
    name: 'HelpCircle',
    label: 'Dúvidas / Ajuda',
    category: 'contato',
    tags: ['ajuda', 'duvida', 'faq', 'pergunta', 'informacao'],
    component: HelpCircle,
  },
  Info: {
    name: 'Info',
    label: 'Informações Importantes',
    category: 'contato',
    tags: ['info', 'detalhe', 'aviso', 'noticia'],
    component: Info,
  },
  Bell: {
    name: 'Bell',
    label: 'Notificação / Sino',
    category: 'contato',
    tags: ['sino', 'aviso', 'alerta', 'lembrete'],
    component: Bell,
  },

  // Garantia & Geral
  ShieldCheck: {
    name: 'ShieldCheck',
    label: 'Segurança & Certificado',
    category: 'geral',
    tags: ['seguranca', 'protecao', 'terapeutas', 'confianca', 'garantia'],
    component: ShieldCheck,
  },
  Shield: {
    name: 'Shield',
    label: 'Escudo Protetor',
    category: 'geral',
    tags: ['escudo', 'protecao', 'tranquilidade'],
    component: Shield,
  },
  Check: {
    name: 'Check',
    label: 'Check Simples',
    category: 'geral',
    tags: ['check', 'confirmado', 'incluso', 'positivo', 'sim'],
    component: Check,
  },
  CheckCircle2: {
    name: 'CheckCircle2',
    label: 'Check Circular',
    category: 'geral',
    tags: ['check', 'circulo', 'completo', 'etapa', 'sucesso'],
    component: CheckCircle2,
  },
  CheckCheck: {
    name: 'CheckCheck',
    label: 'Duplo Check',
    category: 'geral',
    tags: ['check', 'lido', 'confirmado'],
    component: CheckCheck,
  },
  ThumbsUp: {
    name: 'ThumbsUp',
    label: 'Aprovado / Positivo',
    category: 'geral',
    tags: ['positivo', 'aprovado', 'joinha', 'recomendo'],
    component: ThumbsUp,
  },
  Zap: {
    name: 'Zap',
    label: 'Energia Renovada',
    category: 'geral',
    tags: ['energia', 'raio', 'vitalidade', 'rapido', 'renovacao'],
    component: Zap,
  },
  Activity: {
    name: 'Activity',
    label: 'Saúde & Frequência',
    category: 'geral',
    tags: ['saude', 'frequencia', 'corpo', 'circulacao'],
    component: Activity,
  },
  Eye: {
    name: 'Eye',
    label: 'Olhar Atento',
    category: 'geral',
    tags: ['olho', 'visao', 'atencao', 'detalhe'],
    component: Eye,
  },
  Camera: {
    name: 'Camera',
    label: 'Fotografia & Memória',
    category: 'geral',
    tags: ['foto', 'camera', 'memoria', 'registro'],
    component: Camera,
  },
  Package: {
    name: 'Package',
    label: 'Pacote Especial',
    category: 'geral',
    tags: ['pacote', 'caixa', 'combo', 'kit'],
    component: Package,
  },
  ShoppingBag: {
    name: 'ShoppingBag',
    label: 'Sacola de Mimos',
    category: 'geral',
    tags: ['sacola', 'compras', 'mimo', 'produtos'],
    component: ShoppingBag,
  },
  Ticket: {
    name: 'Ticket',
    label: 'Voucher / Ingresso',
    category: 'geral',
    tags: ['ticket', 'voucher', 'cupom', 'experiencia'],
    component: Ticket,
  },
  Footprints: {
    name: 'Footprints',
    label: 'Spa dos Pés / Pegadas',
    category: 'spa',
    tags: ['pe', 'pes', 'passos', 'pegadas', 'spa dos pes', 'escalda-pes', 'relaxamento'],
    component: Footprints,
  },
  GlassWater: {
    name: 'GlassWater',
    label: 'Copo de Água / Cristal',
    category: 'spa',
    tags: ['agua', 'cristal', 'taca', 'welcome drink', 'hidratacao'],
    component: GlassWater,
  },
  Lamp: {
    name: 'Lamp',
    label: 'Iluminação Quente / Abajur',
    category: 'spa',
    tags: ['luz', 'luminaria', 'abajur', 'ambiente', '3000k', 'calma'],
    component: Lamp,
  },
  Scissors: {
    name: 'Scissors',
    label: 'Tesoura Cuidado Capilar',
    category: 'spa',
    tags: ['tesoura', 'cabelo', 'terapia capilar', 'corte', 'fios'],
    component: Scissors,
  },
  SmilePlus: {
    name: 'SmilePlus',
    label: 'Sorriso Positivo',
    category: 'spa',
    tags: ['sorriso', 'alegria', 'bem-estar', 'felicidade'],
    component: SmilePlus,
  },
  Users: {
    name: 'Users',
    label: 'Equipe Terapêutica / Dupla',
    category: 'contato',
    tags: ['terapeutas', 'equipe', 'dupla', 'atendimento', 'pessoas', 'andressa', 'luciana'],
    component: Users,
  },
  VolumeX: {
    name: 'VolumeX',
    label: 'Silêncio / Mudo',
    category: 'spa',
    tags: ['silencio', 'mudo', 'sem som', 'paz', 'tranquilidade'],
    component: VolumeX,
  },
  Plus: {
    name: 'Plus',
    label: 'Adicionar / Mais',
    category: 'geral',
    tags: ['mais', 'adicionar', 'novo', 'plus', 'incluir'],
    component: Plus,
  },
  PlusCircle: {
    name: 'PlusCircle',
    label: 'Complemento / Adicional',
    category: 'geral',
    tags: ['complemento', 'mais', 'circulo', 'adicional', 'upgrade'],
    component: PlusCircle,
  },
  ExternalLink: {
    name: 'ExternalLink',
    label: 'Link Externo',
    category: 'geral',
    tags: ['link', 'externo', 'abrir', 'janela'],
    component: ExternalLink,
  },
  RotateCcw: {
    name: 'RotateCcw',
    label: 'Restaurar / Voltar',
    category: 'geral',
    tags: ['restaurar', 'recarregar', 'voltar', 'reset'],
    component: RotateCcw,
  },
  X: {
    name: 'X',
    label: 'Fechar / Cancelar',
    category: 'geral',
    tags: ['fechar', 'cancelar', 'sair', 'x'],
    component: X,
  },
  Menu: {
    name: 'Menu',
    label: 'Menu Hamburguer',
    category: 'geral',
    tags: ['menu', 'navegacao', 'linhas', 'gaveta'],
    component: Menu,
  },

  // Setas & Navegação Direcional
  ArrowRight: {
    name: 'ArrowRight',
    label: 'Seta Direita / Próximo',
    category: 'setas',
    tags: ['seta', 'direita', 'proximo', 'seguir', 'avancar', 'acao', 'conhecer'],
    component: ArrowRight,
  },
  ArrowLeft: {
    name: 'ArrowLeft',
    label: 'Seta Esquerda / Voltar',
    category: 'setas',
    tags: ['seta', 'esquerda', 'voltar', 'anterior'],
    component: ArrowLeft,
  },
  ArrowUp: {
    name: 'ArrowUp',
    label: 'Seta Cima / Topo',
    category: 'setas',
    tags: ['seta', 'cima', 'topo', 'subir', 'voltar ao topo', 'inicio'],
    component: ArrowUp,
  },
  ArrowDown: {
    name: 'ArrowDown',
    label: 'Seta Baixo / Rolar',
    category: 'setas',
    tags: ['seta', 'baixo', 'descer', 'rolar'],
    component: ArrowDown,
  },
  ArrowUpRight: {
    name: 'ArrowUpRight',
    label: 'Seta Diagonal Externa',
    category: 'setas',
    tags: ['seta', 'diagonal', 'externo', 'link', 'abrir', 'ir'],
    component: ArrowUpRight,
  },
  ArrowDownRight: {
    name: 'ArrowDownRight',
    label: 'Seta Diagonal Baixo',
    category: 'setas',
    tags: ['seta', 'diagonal', 'baixo'],
    component: ArrowDownRight,
  },
  ChevronRight: {
    name: 'ChevronRight',
    label: 'Chevron Direita',
    category: 'setas',
    tags: ['chevron', 'direita', 'avancar', 'proximo'],
    component: ChevronRight,
  },
  ChevronLeft: {
    name: 'ChevronLeft',
    label: 'Chevron Esquerda',
    category: 'setas',
    tags: ['chevron', 'esquerda', 'anterior', 'voltar'],
    component: ChevronLeft,
  },
  ChevronDown: {
    name: 'ChevronDown',
    label: 'Chevron Baixo / Expandir',
    category: 'setas',
    tags: ['chevron', 'baixo', 'abrir', 'expandir', 'acordeon', 'descer', 'rolar'],
    component: ChevronDown,
  },
  ChevronUp: {
    name: 'ChevronUp',
    label: 'Chevron Cima / Recolher',
    category: 'setas',
    tags: ['chevron', 'cima', 'fechar', 'recolher', 'subir'],
    component: ChevronUp,
  },
};

export const ICON_CATEGORIES = [
  { key: 'all', label: 'Todos os Ícones' },
  { key: 'spa', label: 'SPA & Bem-Estar' },
  { key: 'luxo', label: 'Luxo & Presentes' },
  { key: 'tempo-local', label: 'Tempo & Local' },
  { key: 'contato', label: 'Contato & Social' },
  { key: 'setas', label: 'Setas & Navegação' },
  { key: 'geral', label: 'Qualidade & Geral' },
] as const;
